services:
  - type: web
    name: profitbot-three
    env: docker
    plan: free
    region: oregon 
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8774183137:AAF2O1EFz_2XjtF2LHA3ALmIuRvuTEBLtmM
      - key: TELEGRAM_CHAT_ID
        value: "8506152391"
      - key: BOT_PROFILE
        value: "three_dollar"
      - key: INITIAL_CAPITAL
        value: "3.00"

  - type: web
    name: profitbot-ten
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8774183137:AAF2O1EFz_2XjtF2LHA3ALmIuRvuTEBLtmM
      - key: TELEGRAM_CHAT_ID
        value: "8506152391"
      - key: BOT_PROFILE
        value: "ten_dollar"
      - key: INITIAL_CAPITAL
        value: "10.00"
