services:
  - type: web
    name: profitbot-pro
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --strategy scalper70 --leverage 20 --capital 3 --max_trades 15 --port $PORT
    envVars:
      - key: PORT
        value: 5000
      - key: EXCHANGE
        value: bybit
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: USE_REAL_EXCHANGE
        value: "true"
      - key: USE_TESTNET
        value: "true"
      - key: INITIAL_CAPITAL
        value: "3.0"
      - key: LEVERAGE
        value: "20"
      - key: MAX_CONCURRENT_TRADES
        value: "15"
      - key: TAKE_PROFIT_PCT
        value: "0.03"
